# -*- coding: utf-8 -*-
"""AI_imaging_Coding_Case_Study_and_Report (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSkezCdqY6kL1v1GW6XX-wRTpDd9H9gV

Install Ollama and start the server
"""

# =====================================================================
# CELL 1 (FIXED v2) — INSTALL OLLAMA
# =====================================================================
import subprocess, sys, time, shutil, os, importlib.util
from pathlib import Path

for mod, pkg in {"skimage": "scikit-image", "PIL": "Pillow"}.items():
    if importlib.util.find_spec(mod) is None:
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", pkg], check=False)

# The Ollama installer extracts a .tar.zst archive and aborts if zstd is
# absent. It removes any existing install BEFORE extracting, so a failure here
# leaves no working binary at all — install zstd first.
if shutil.which("zstd") is None:
    print("installing zstd (required by the Ollama installer) ...")
    subprocess.run("apt-get update -qq && apt-get install -y -qq zstd",
                   shell=True, capture_output=True, text=True)
print("zstd:", shutil.which("zstd") or "STILL MISSING")

def find_ollama():
    p = shutil.which("ollama")
    if p: return p
    for c in ["/usr/local/bin/ollama", "/usr/bin/ollama", "/opt/ollama/bin/ollama"]:
        if Path(c).is_file() and os.access(c, os.X_OK): return c
    return None

OLLAMA_BIN = find_ollama()

if OLLAMA_BIN is None:
    print("\ninstalling Ollama ...")
    res = subprocess.run("curl -fsSL https://ollama.com/install.sh | sh",
                         shell=True, capture_output=True, text=True)
    print(res.stdout[-1500:])
    if res.stderr.strip(): print("stderr:", res.stderr[-1500:])
    OLLAMA_BIN = find_ollama()

# Fallback: the .tgz build is gzip, so it needs no zstd at all
if OLLAMA_BIN is None:
    print("\nscript install failed — trying the direct tarball ...")
    subprocess.run(
        "curl -fsSL https://ollama.com/download/ollama-linux-amd64.tgz -o /tmp/o.tgz "
        "&& mkdir -p /usr/local && tar -C /usr/local -xzf /tmp/o.tgz",
        shell=True, capture_output=True, text=True)
    OLLAMA_BIN = find_ollama()

if OLLAMA_BIN is None:
    raise RuntimeError("Ollama still not installed — paste the output above.")

os.environ["PATH"] = f"{Path(OLLAMA_BIN).parent}:{os.environ['PATH']}"
print("\nbinary :", OLLAMA_BIN)
print("version:", subprocess.run([OLLAMA_BIN, "--version"],
                                 capture_output=True, text=True).stdout.strip())

subprocess.Popen([OLLAMA_BIN, "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

import requests
OLLAMA_HOST = "http://localhost:11434"
for attempt in range(12):
    try:
        r = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=5)
        print("server UP |", [m["name"] for m in r.json().get("models", [])] or "no models yet")
        break
    except Exception:
        time.sleep(3)
else:
    raise RuntimeError("server did not start — re-run this cell")

import torch
print("\nCUDA:", torch.cuda.is_available())
if not torch.cuda.is_available():
    print("CPU mode — qwen2.5vl:7b will be ~1-3 min per image.")
    print("Consider N_VARIABILITY_RUNS = 3 and EPOCHS = 15 to keep the run finishable.")

# =====================================================================
# CELL 1b — CPU BUDGET CHECK (run before pulling the 5 GB model)
# =====================================================================
import numpy as np, base64, time, requests
from PIL import Image

yy, xx = np.mgrid[0:256, 0:256]
_p = np.full((256,256), 30, np.uint8)
for cy,cx,r in [(90,90,34),(170,165,22)]:
    _p[(yy-cy)**2+(xx-cx)**2 < r**2] = 220
Image.fromarray(_p).save("/tmp/probe.png")
probe_b64 = base64.b64encode(open("/tmp/probe.png","rb").read()).decode()

# moondream is ~1.7 GB and pulls in about a minute. Use it to measure this
# runtime's actual inference speed before committing to a 5 GB download.
subprocess.run([OLLAMA_BIN, "pull", "moondream"], check=False)

t0 = time.time()
r = requests.post(f"{OLLAMA_HOST}/api/generate", json={
    "model": "moondream",
    "prompt": "How many bright circular objects are in this image?",
    "images": [probe_b64], "stream": False}, timeout=900)
el = time.time() - t0
print(f"moondream latency: {el:.1f}s")
print("response:", r.json().get("response","").strip()[:200])
print(f"\nqwen2.5vl:7b is roughly 4-6x heavier -> estimate {el*5:.0f}s per image")
print(f"7 VLM calls at that rate = {el*5*7/60:.0f} min, plus a ~5 GB download")

""" Resolving a vision model that actually works
This is the fix for the mllama problem. It doesn't trust ollama pull succeeding — it sends a real image and only accepts a model that returns text.
"""

# =====================================================================
# CELL 2 — FIND A VISION MODEL THAT ACTUALLY RUNS
# =====================================================================
import base64, numpy as np
from PIL import Image

OLLAMA_HOST = "http://localhost:11434"

# Ordered by preference. The brief's model first; alternatives after.
VISION_CANDIDATES = [
    "llama3.2-vision",   # brief's choice — needs Ollama >= 0.4.0
    "qwen2.5vl:7b",      # strong alternative
    "qwen2.5vl:3b",      # lighter
    "llava:7b",
    "llava-phi3",
    "moondream",         # ~1.7 GB, last resort
]

def _probe_image(path="/tmp/probe.png"):
    """Two bright discs on a dark field — trivial, but a model that cannot
    report this will not manage real microscopy."""
    yy, xx = np.mgrid[0:256, 0:256]
    img = np.full((256, 256), 30, np.uint8)
    for cy, cx, rad in [(90, 90, 34), (170, 165, 22)]:
        img[(yy-cy)**2 + (xx-cx)**2 < rad**2] = 220
    Image.fromarray(img).save(path)
    return path

def encode_image(path):
    return base64.b64encode(open(path, "rb").read()).decode()

def try_vision_model(name, probe_b64, pull_timeout=2400):
    """Pull, then send a real image. Only a successful generate counts."""
    pull = subprocess.run(["ollama", "pull", name],
                          capture_output=True, text=True, timeout=pull_timeout)
    if pull.returncode != 0:
        return False, (pull.stderr or pull.stdout).strip()[-180:], None
    try:
        t0 = time.time()
        resp = requests.post(f"{OLLAMA_HOST}/api/generate", json={
            "model": name,
            "prompt": "How many bright circular objects are in this image?",
            "images": [probe_b64], "stream": False}, timeout=900)
        if resp.status_code != 200:
            return False, resp.text[:180], None
        txt = resp.json().get("response", "").strip()
        if not txt:
            return False, "empty response", None
        return True, txt, round(time.time() - t0, 1)
    except Exception as e:
        return False, f"{type(e).__name__}: {str(e)[:150]}", None

probe_b64 = encode_image(_probe_image())
VISION_MODEL, VLM_LATENCY, VLM_AVAILABLE = None, None, False

for cand in VISION_CANDIDATES:
    print(f"\ntrying {cand} ...")
    ok, msg, lat = try_vision_model(cand, probe_b64)
    if ok:
        VISION_MODEL, VLM_LATENCY, VLM_AVAILABLE = cand, lat, True
        print(f"  WORKS | {lat}s | {msg[:200]}")
        break
    print(f"  failed: {msg}")
    if "mllama" in msg.lower():
        print("  -> Ollama binary too old for this architecture; trying next.")

print("\n" + "="*55)
print(f"VISION MODEL IN USE: {VISION_MODEL}")
print("Name this model in the report — model choice affects every result.")
print("="*55)

# Text-only model for Task 2
subprocess.run(["ollama", "pull", "llama3.2"], check=False)
TEXT_MODEL = "llama3.2"

# =====================================================================
# CELL 3 — CONFIGURATION
# =====================================================================
import json, re, warnings, zipfile
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from skimage.filters import threshold_otsu

PROJECT = Path("/content/biomed-pipeline")
DATA_DIR, FIG_DIR, TAB_DIR = PROJECT/"data", PROJECT/"outputs/figures", PROJECT/"outputs/tables"
for p in (DATA_DIR, FIG_DIR, TAB_DIR): p.mkdir(parents=True, exist_ok=True)

DATASET_URL = "https://github.com/Nickolay-K/Assingnment-3-dataset"
IMG_SIZE, SPLITS = 256, ["train", "val", "test"]
REQUEST_TIMEOUT, N_VARIABILITY_RUNS = 300, 5
VARIABILITY_SEED = None    # unset on purpose — see Cell 12
RANDOM_STATE = 0
np.random.seed(RANDOM_STATE)

plt.rcParams.update({"figure.dpi": 110, "savefig.dpi": 200, "font.size": 9,
                     "axes.grid": True, "grid.alpha": .25,
                     "axes.spines.top": False, "axes.spines.right": False})
INK, SIGNAL, WARM = "#16211E", "#0F6E63", "#B4543A"

FIGURES = {}
def save_fig(fig, n, caption, section=""):
    fig.savefig(FIG_DIR/f"fig{n}.png", bbox_inches="tight", dpi=200)
    FIGURES[n] = {"figure": f"Figure {n}", "file": f"fig{n}.png",
                  "caption": caption, "section": section}
    print(f"  saved fig{n}.png")

# =====================================================================
# CELL 4 — DOWNLOAD AND LOCATE THE DATASET
# =====================================================================
repo = DATA_DIR/"repo"
if not repo.exists():
    subprocess.run(["git", "clone", "--depth", "1", DATASET_URL, str(repo)], check=True)
for z in repo.rglob("*.zip"):
    with zipfile.ZipFile(z) as zf: zf.extractall(DATA_DIR)
    print("extracted", z.name)

def find_root(search=DATA_DIR):
    """Locate the directory holding train/images — repos nest inconsistently."""
    for p in Path(search).rglob("train"):
        if (p/"images").is_dir(): return p.parent
    raise FileNotFoundError("no train/images found")

ROOT = find_root()
META = pd.read_csv(ROOT/"metadata.csv")
print("root:", ROOT)
print(META.groupby("split").agg(images=("image_id","size"),
      mean_objects=("n_objects","mean")).round(1).to_string())
print("\nmetadata.csv gives TRUE object count and density per image —")
print("an answer key that makes later claims measurable rather than asserted.")

""" Grayscale: the decision that matters"""

# =====================================================================
# CELL 5 — GRAYSCALE STRATEGY: LUMA VS BLUE CHANNEL
# =====================================================================
# These are DAPI-like fluorescence images: the generator puts nuclear signal
# in blue (B = I, G = 0.35I, R = 0.12I). PIL's convert("L") applies ITU-R
# 601-2 luma = 0.299R + 0.587G + 0.114B, which here evaluates to ~0.355*I --
# discarding about two-thirds of the dynamic range before segmentation.
def to_gray_luma(rgb):  return np.asarray(Image.fromarray(rgb).convert("L"))
def to_gray_blue(rgb):  return np.asarray(rgb)[..., 2]

train_imgs = sorted((ROOT/"train/images").glob("*.png"))
rows = []
for p in train_imgs[:20]:
    rgb = np.asarray(Image.open(p).convert("RGB"))
    l, b = to_gray_luma(rgb), to_gray_blue(rgb)
    rows.append({"luma_std": l.std(), "blue_std": b.std(),
                 "luma_max": l.max(), "blue_max": b.max(),
                 "luma_otsu": threshold_otsu(l), "blue_otsu": threshold_otsu(b)})
gray_cmp = pd.DataFrame(rows)

print("Averaged over 20 training images")
print(f"  contrast (std)  luma {gray_cmp.luma_std.mean():6.2f}   blue {gray_cmp.blue_std.mean():6.2f}"
      f"   ratio {gray_cmp.blue_std.mean()/gray_cmp.luma_std.mean():.2f}x")
print(f"  peak value      luma {gray_cmp.luma_max.mean():6.1f}   blue {gray_cmp.blue_max.mean():6.1f}")
gray_cmp.to_csv(TAB_DIR/"grayscale_strategy.csv", index=False)

GRAY_FN = to_gray_blue
print("\nUsing the BLUE CHANNEL.")

# =====================================================================
# CELL 6 — PREPROCESS TO GRAYSCALE 256x256 + MANIFEST
# =====================================================================
def load_image_gray(path): return GRAY_FN(np.asarray(Image.open(path).convert("RGB")))
def load_mask(path):       return np.asarray(Image.open(path).convert("L")) > 127

def ensure_size(arr, size=IMG_SIZE, is_mask=False):
    """No-op for this dataset (already 256x256), kept so the pipeline is not
    silently dependent on that. Masks use NEAREST — smooth interpolation would
    invent label values belonging to no class."""
    if arr.shape[:2] == (size, size): return arr
    return np.asarray(Image.fromarray(arr).resize(
        (size, size), resample=Image.NEAREST if is_mask else Image.BILINEAR))

rows = []
for split in SPLITS:
    for ip in sorted((ROOT/split/"images").glob("*.png")):
        mp = ROOT/split/"masks"/f"{ip.stem}.png"
        arr = ensure_size(load_image_gray(ip))
        rows.append({"image_id": ip.stem, "split": split, "image": str(ip),
                     "mask": str(mp) if mp.exists() else None,
                     "height": arr.shape[0], "width": arr.shape[1],
                     "mean_intensity": float(arr.mean()), "std_intensity": float(arr.std())})

manifest = (pd.DataFrame(rows)
            .merge(META[["image_id","density","n_objects","area_fraction"]],
                   on="image_id", how="left")
            .rename(columns={"n_objects": "true_n_objects"}))
manifest.to_csv(TAB_DIR/"manifest.csv", index=False)

print(manifest.groupby("split").agg(n=("image_id","size"),
      with_mask=("mask", lambda s: s.notna().sum())).to_string())
print(f"all 256x256: {((manifest.height==IMG_SIZE)&(manifest.width==IMG_SIZE)).all()}"
      "  -> resizing introduces no aspect distortion here")

rep = manifest[(manifest.split=="test") & (manifest.density=="normal")].iloc[0]
REP_IMAGE = rep["image"]
print(f"\nrepresentative image: {rep.image_id} ({rep.density}, {int(rep.true_n_objects)} nuclei)")

# =====================================================================
# CELL 7 — FIGURE 1: SAMPLES ACROSS DENSITY REGIMES
# =====================================================================
regimes = ["sparse", "normal", "dense", "clustered"]
picks = [manifest[manifest.density==d].iloc[0] for d in regimes if (manifest.density==d).any()]

fig, axes = plt.subplots(2, len(picks), figsize=(3.1*len(picks), 6.4))
axes = np.atleast_2d(axes)
for j, r in enumerate(picks):
    axes[0,j].imshow(load_image_gray(r["image"]), cmap="gray", vmin=0, vmax=255)
    axes[0,j].set_title(f"{r.density}\n{r.image_id} — {int(r.true_n_objects)} nuclei", fontsize=8)
    axes[1,j].imshow(load_mask(r["mask"]), cmap="gray")
    axes[1,j].set_title("ground-truth mask", fontsize=8)
    for i in (0,1): axes[i,j].axis("off"); axes[i,j].grid(False)
fig.suptitle("Sample images by density regime (blue channel)", y=0.995)
fig.tight_layout()
save_fig(fig, 1, "Representative images from each density regime with ground-truth "
         "masks. Counts from metadata.csv.", "Task 1 — EDA")
plt.show()

# =====================================================================
# CELL 8 — FIGURE 2: INTENSITY HISTOGRAMS
# =====================================================================
rng = np.random.default_rng(RANDOM_STATE)
sample = manifest.iloc[rng.choice(len(manifest), size=6, replace=False)]

fig, axes = plt.subplots(1, 2, figsize=(11, 3.8))
for (_, r), c in zip(sample.iterrows(), plt.cm.viridis(np.linspace(0,.85,len(sample)))):
    axes[0].hist(load_image_gray(r["image"]).ravel(), bins=64, range=(0,255),
                 histtype="step", lw=1.2, color=c, label=f"{r.image_id} ({r.density})")
axes[0].set_yscale("log"); axes[0].legend(fontsize=6)
axes[0].set_title("Individual images (log count)"); axes[0].set_xlabel("blue-channel intensity")

pooled = np.concatenate([load_image_gray(r["image"]).ravel() for _, r in manifest.iterrows()])
axes[1].hist(pooled, bins=64, range=(0,255), color=SIGNAL, alpha=.85)
axes[1].axvline(threshold_otsu(pooled), color=WARM, ls="--", lw=1.5,
                label=f"global Otsu = {threshold_otsu(pooled):.0f}")
axes[1].set_yscale("log"); axes[1].legend(fontsize=8)
axes[1].set_title(f"Pooled, all {len(manifest)} images"); axes[1].set_xlabel("blue-channel intensity")

fig.tight_layout()
save_fig(fig, 2, "Blue-channel intensity histograms, individual and pooled. The dark-field "
         "mode and separated bright tail are the bimodality Otsu relies on.", "Task 1 — EDA")
plt.show()
print("Strong bimodality -> predicts Otsu will threshold well. Task 2 tests that.")

# =====================================================================
# CELL 9 — NAIVE AND STRUCTURED PROMPTS
# =====================================================================
NAIVE_PROMPT = "What do you see in this medical image?"

STRUCTURED_PROMPT = """You are describing a biomedical image for a data catalogue.

Your task is DESCRIPTIVE, not diagnostic. Do not state or imply any clinical
diagnosis, disease, or patient outcome. Describe only what is visually present.

If you cannot determine a field from the image alone, use the string
"uncertain". Answering "uncertain" is correct and expected when the evidence is
insufficient; guessing is not.

Respond with a single JSON object and nothing else. No preamble, no
explanation, no markdown code fences.

Required schema:
{
  "modality": one of ["microscopy", "histology", "x-ray", "ct", "mri",
                      "ultrasound", "retinal", "dermoscopy", "other",
                      "uncertain"],
  "tissue_type": short lowercase string, or "uncertain",
  "notable_features": array of 1 to 4 short descriptive phrases about visible
                      structures, texture, or spatial arrangement,
  "image_quality": one of ["good", "moderate", "poor", "uncertain"]
}"""

print(STRUCTURED_PROMPT)

# =====================================================================
# CELL 10 — VLM QUERY + ROBUST JSON EXTRACTION
# =====================================================================
def query_vlm(prompt, image_path, model=None, seed=None, timeout=REQUEST_TIMEOUT):
    payload = {"model": model or VISION_MODEL, "prompt": prompt,
               "images": [encode_image(image_path)], "stream": False}
    if seed is not None: payload["options"] = {"seed": seed}
    t0 = time.time()
    r = requests.post(f"{OLLAMA_HOST}/api/generate", json=payload, timeout=timeout)
    r.raise_for_status()
    return {"response": r.json().get("response",""), "elapsed_s": round(time.time()-t0,2)}

def extract_json(text):
    """Three strategies, strictest first. The status is kept, not discarded:
    how often a model ignores an explicit output contract is itself a finding."""
    if not text or not text.strip(): return None, "empty"
    try: return json.loads(text.strip()), "clean"
    except json.JSONDecodeError: pass
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        try: return json.loads(m.group(1)), "fenced"
        except json.JSONDecodeError: pass
    s = text.find("{")
    if s != -1:
        depth = 0
        for i, ch in enumerate(text[s:], s):
            if ch == "{": depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    try: return json.loads(text[s:i+1]), "embedded"
                    except json.JSONDecodeError: break
    return None, "unparseable"

VLM_FIELDS = ["modality","tissue_type","notable_features","image_quality"]
ALLOWED_MODALITY = {"microscopy","histology","x-ray","ct","mri","ultrasound",
                    "retinal","dermoscopy","other","uncertain"}
ALLOWED_QUALITY = {"good","moderate","poor","uncertain"}

def validate_vlm_record(rec):
    """Schema compliance is measured, not assumed."""
    if rec is None:
        return {"valid": False, "missing": VLM_FIELDS, "violations": [], "n_features": 0}
    missing = [f for f in VLM_FIELDS if f not in rec]
    viol = []
    if str(rec.get("modality","")).lower() not in ALLOWED_MODALITY: viol.append("modality")
    if str(rec.get("image_quality","")).lower() not in ALLOWED_QUALITY: viol.append("image_quality")
    fe = rec.get("notable_features", [])
    return {"valid": not missing and not viol, "missing": missing, "violations": viol,
            "n_features": len(fe) if isinstance(fe, list) else 0}

# =====================================================================
# CELL 11 — PROMPT COMPARISON
# =====================================================================
# The useful question is not which answer is *better* — neither is verifiable
# without ground truth — but which is *usable*: parseable, schema-compliant,
# and hedged where it should be.
rows = []
for name, prompt in [("naive", NAIVE_PROMPT), ("structured", STRUCTURED_PROMPT)]:
    try:
        raw = query_vlm(prompt, REP_IMAGE)
        parsed, status = extract_json(raw["response"])
        chk = validate_vlm_record(parsed)
        rows.append({"prompt": name, "parse_status": status, "schema_valid": chk["valid"],
                     "missing": ",".join(chk["missing"]), "chars": len(raw["response"]),
                     "elapsed_s": raw["elapsed_s"], "raw": raw["response"]})
    except Exception as e:
        rows.append({"prompt": name, "parse_status": f"error: {type(e).__name__}",
                     "schema_valid": False, "missing": "", "chars": 0,
                     "elapsed_s": None, "raw": str(e)[:300]})

prompt_cmp = pd.DataFrame(rows)
prompt_cmp.to_csv(TAB_DIR/"prompt_comparison.csv", index=False)
print(prompt_cmp[["prompt","parse_status","schema_valid","chars","elapsed_s"]].to_string(index=False))
for _, r in prompt_cmp.iterrows():
    print(f"\n--- {r['prompt']} ---\n{r['raw'][:800]}")

# =====================================================================
# CELL 12 — RUN-TO-RUN VARIABILITY, IDENTICAL PROMPT
# =====================================================================
# The seed is deliberately unset. Fixing it would make the model
# near-deterministic and conceal exactly the instability being measured.
rows = []
for i in range(N_VARIABILITY_RUNS):
    try:
        raw = query_vlm(STRUCTURED_PROMPT, REP_IMAGE, seed=VARIABILITY_SEED)
        parsed, status = extract_json(raw["response"])
        chk = validate_vlm_record(parsed)
        rows.append({"run": i+1, "parse_status": status, "schema_valid": chk["valid"],
                     "modality": (parsed or {}).get("modality"),
                     "tissue_type": (parsed or {}).get("tissue_type"),
                     "image_quality": (parsed or {}).get("image_quality"),
                     "n_features": chk["n_features"],
                     "notable_features": json.dumps((parsed or {}).get("notable_features", [])),
                     "elapsed_s": raw["elapsed_s"]})
    except Exception as e:
        rows.append({"run": i+1, "parse_status": f"error: {type(e).__name__}",
                     "schema_valid": False, "modality": None, "tissue_type": None,
                     "image_quality": None, "n_features": 0,
                     "notable_features": "[]", "elapsed_s": None})
    print(f"  run {i+1}: {rows[-1]['parse_status']} | modality={rows[-1]['modality']}")

vlm_runs = pd.DataFrame(rows)
vlm_runs.to_csv(TAB_DIR/"vlm_variability_runs.csv", index=False)

summary = []
for f in ["modality","tissue_type","image_quality"]:
    v = vlm_runs[f].dropna()
    if v.empty:
        summary.append({"field": f, "n_distinct": 0, "modal_value": None, "agreement": np.nan})
    else:
        c = v.value_counts()
        summary.append({"field": f, "n_distinct": v.nunique(), "modal_value": c.index[0],
                        "agreement": round(c.iloc[0]/len(v), 3)})
nf = vlm_runs.n_features
summary.append({"field": "n_notable_features", "n_distinct": nf.nunique(),
                "modal_value": f"range {nf.min()}-{nf.max()}",
                "agreement": round((nf==nf.mode().iloc[0]).mean(),3) if not nf.mode().empty else np.nan})

vlm_var = pd.DataFrame(summary)
vlm_var.to_csv(TAB_DIR/"vlm_variability_summary.csv", index=False)
print("\n" + vlm_var.to_string(index=False))
print(f"\nModel used: {VISION_MODEL}")
print(f"Fields differing across identical calls: "
      f"{vlm_var[vlm_var.agreement < 1.0]['field'].tolist() or 'none'}")
print("\nNote: the VLM's modality and tissue_type claims cannot be")
print("scored for correctness — there is no ground truth for them. Task 2's")
print("numbers can be. That asymmetry IS the trustworthiness argument.")

""" Classical features & numbers-first LLM - Otsu segmentation and region features"""

# =====================================================================
# CELL 13 — OTSU + MORPHOLOGY + REGIONPROPS
# =====================================================================
from skimage.measure import label, regionprops_table
from skimage.morphology import disk, remove_small_objects, remove_small_holes

MIN_OBJECT_AREA, MORPH_RADIUS = 30, 2

# scikit-image renamed morphology params at 0.26; these keep the notebook
# working on whichever version Colab ships.
def _opening(b, se):
    try:    from skimage.morphology import opening;        return opening(b, se)
    except ImportError:
        from skimage.morphology import binary_opening;     return binary_opening(b, se)

def _closing(b, se):
    try:    from skimage.morphology import closing;        return closing(b, se)
    except ImportError:
        from skimage.morphology import binary_closing;     return binary_closing(b, se)

def _drop_small(b, a):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        try:    return remove_small_objects(b, min_size=a)
        except TypeError: return remove_small_objects(b, a)

def _fill_small(b, a):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        try:    return remove_small_holes(b, area_threshold=a)
        except TypeError: return remove_small_holes(b, a)

def segment_otsu(img, min_area=MIN_OBJECT_AREA, morph_radius=MORPH_RADIUS):
    """Otsu threshold + cleanup. Returns (binary_mask, threshold).

    Order matters: opening (erode-dilate) removes specks BEFORE closing
    (dilate-erode) can seal them into objects. The reverse order fuses
    adjacent debris into spurious components the size filter then keeps.
    """
    thresh = threshold_otsu(img)
    b = img > thresh
    se = disk(morph_radius)
    b = _opening(b, se)
    b = _closing(b, se)
    b = _drop_small(b, min_area)
    b = _fill_small(b, min_area)
    return b, float(thresh)

def extract_region_features(binary, intensity_img):
    """Per-object table. Intensity props measured against the grayscale image,
    not the mask, so mean_intensity is a real measurement."""
    labels = label(binary)
    cols = ["label","area","eccentricity","solidity","mean_intensity",
            "perimeter","equivalent_diameter","extent","orientation"]
    if labels.max() == 0:
        return pd.DataFrame(columns=cols)
    return pd.DataFrame(regionprops_table(labels, intensity_image=intensity_img,
                                          properties=tuple(cols)))

def summarise_regions(feat_df, shape=(IMG_SIZE, IMG_SIZE)):
    """Image-level numbers. These are the ONLY quantities the LLM interprets,
    and they are computed here — not by the model."""
    total = shape[0]*shape[1]
    if feat_df.empty:
        return {"n_objects":0,"mean_area":0.0,"median_area":0.0,"std_area":0.0,
                "coverage_pct":0.0,"mean_eccentricity":np.nan,
                "mean_solidity":np.nan,"mean_intensity":np.nan}
    return {"n_objects": int(len(feat_df)),
            "mean_area": round(float(feat_df.area.mean()),2),
            "median_area": round(float(feat_df.area.median()),2),
            "std_area": round(float(feat_df.area.std(ddof=0)),2),
            "coverage_pct": round(100*float(feat_df.area.sum())/total,2),
            "mean_eccentricity": round(float(feat_df.eccentricity.mean()),3),
            "mean_solidity": round(float(feat_df.solidity.mean()),3),
            "mean_intensity": round(float(feat_df.mean_intensity.mean()),2)}

# Worked example — include this table in the report
_img = load_image_gray(REP_IMAGE)
_mask, _thr = segment_otsu(_img)
_feats = extract_region_features(_mask, _img)
_feats.to_csv(TAB_DIR/"example_regionprops_table.csv", index=False)
print(f"{rep.image_id}: Otsu threshold {_thr:.1f}, {len(_feats)} objects "
      f"(true {int(rep.true_n_objects)})")
print(_feats.head(6).round(3).to_string(index=False))

# =====================================================================
# CELL 14 — OTSU COUNT ACCURACY VS GROUND TRUTH
# =====================================================================
rows = []
for _, r in manifest.iterrows():
    img = load_image_gray(r["image"])
    mask, thr = segment_otsu(img)
    rows.append({"image_id": r.image_id, "split": r.split, "density": r.density,
                 "true_n_objects": r.true_n_objects, "otsu_threshold": round(thr,1),
                 **summarise_regions(extract_region_features(mask, img))})
otsu_all = pd.DataFrame(rows)
otsu_all["count_error"] = otsu_all.n_objects - otsu_all.true_n_objects
otsu_all["count_pct_error"] = 100*otsu_all.count_error/otsu_all.true_n_objects
otsu_all.to_csv(TAB_DIR/"otsu_summary.csv", index=False)

print("OTSU COUNT ACCURACY BY DENSITY REGIME")
print(otsu_all.groupby("density").agg(n=("image_id","size"),
      true=("true_n_objects","mean"), otsu=("n_objects","mean"),
      pct_error=("count_pct_error","mean")).round(1).to_string())
print(f"\noverall: {otsu_all.count_pct_error.mean():+.1f}%")

# =====================================================================
# CELL 15 — COUNT-ERROR DECOMPOSITION
# =====================================================================
# Count connected components in the GROUND-TRUTH mask, which is perfect by
# construction. Any shortfall there is a ceiling imposed by binary
# segmentation + connected components — touching nuclei form one component —
# and is independent of the method that produced the mask.
rows = []
for _, r in manifest[manifest["mask"].notna()].iterrows():
    gt = load_mask(r["mask"])
    rows.append({"image_id": r.image_id, "density": r.density,
                 "true_n_objects": r.true_n_objects,
                 "cc_from_perfect_mask": int(label(gt).max())})
ceiling = pd.DataFrame(rows)
ceiling["ceiling_pct_error"] = 100*(ceiling.cc_from_perfect_mask -
                                    ceiling.true_n_objects)/ceiling.true_n_objects

decomp = (otsu_all[["image_id","density","count_pct_error"]]
          .merge(ceiling[["image_id","ceiling_pct_error"]], on="image_id")
          .groupby("density").agg(otsu_error=("count_pct_error","mean"),
                                  formulation_ceiling=("ceiling_pct_error","mean")).round(1))
decomp["attributable_to_otsu"] = (decomp.otsu_error - decomp.formulation_ceiling).round(1)
decomp.to_csv(TAB_DIR/"count_error_decomposition.csv")

print("COUNT ERROR DECOMPOSITION (%)")
print(decomp.to_string())
print("\nWhere the ceiling dominates, NO binary method — Otsu or U-Net — can")
print("recover the true count. Instance segmentation (labels/ or watershed)")
print("is the only route. This bounds Task 3 too.")

# =====================================================================
# FIGURE 6 — CORRUPTION PROPAGATION
# =====================================================================
# Replaces the previous fig6 cell. The only change is rendering: an
# all-foreground mask is pure white, which was invisible against the white
# figure background and read as a missing plot. Explicit vmin/vmax, a coloured
# border and the foreground percentage in the title make the pathological case
# legible — it is the most important panel in the figure.
src = corruption.iloc[0]["image"].rsplit("_", 1)[0]

panels = [(ROOT/"test/images"/f"{src}.png",                        "clean"),
          (ROOT/"test_corrupted/images"/f"{src}_blur.png",         "heavy blur"),
          (ROOT/"test_corrupted/images"/f"{src}_lowcontrast.png",  "low contrast")]

fig, axes = plt.subplots(2, 3, figsize=(11, 7))
for col, (p, name) in enumerate(panels):
    if not Path(p).exists():
        axes[0, col].axis("off"); axes[1, col].axis("off")
        continue

    img = load_image_gray(p)

    # Top row — the input. Fixed 0-255 scaling so the three panels are
    # directly comparable; autoscaling would hide the contrast collapse.
    axes[0, col].imshow(img, cmap="gray", vmin=0, vmax=255)
    axes[0, col].set_title(f"{name}\nmean {img.mean():.1f}, std {img.std():.1f}",
                           fontsize=8)
    axes[0, col].axis("off"); axes[0, col].grid(False)

    # Bottom row — the resulting U-Net mask.
    m = segment_unet(img, model)
    axes[1, col].imshow(m, cmap="gray", vmin=0, vmax=1)
    axes[1, col].set_facecolor("#dddddd")
    for s in axes[1, col].spines.values():
        s.set_visible(True); s.set_color(WARM); s.set_linewidth(1.5)
    axes[1, col].set_title(
        f"U-Net mask: {label(m).max()} components ({100*m.mean():.0f}% foreground)",
        fontsize=8)
    axes[1, col].set_xticks([]); axes[1, col].set_yticks([]); axes[1, col].grid(False)

fig.suptitle(f"Corruption propagation, {src}", y=0.995)
fig.tight_layout()
save_fig(fig, 6,
         "Provided corrupted test images and the resulting U-Net masks. Low contrast "
         "collapses the intensity spread (std 25.8 to 3.9) and drives the network to "
         "label the entire field as foreground; heavy blur leaves the mean almost "
         "unchanged but merges and loses objects. The pipeline flagged neither.",
         "Extension — robustness")
plt.show()

# Restate the numbers under the figure so the caption is checkable
for _, r in corruption[corruption.image.str.startswith(src)].iterrows():
    print(f"  {r['image']:<26} mask IoU {r.mask_iou_vs_clean:.3f} | "
          f"count {r.n_clean}->{r.n_corrupt} | quality_flag = {r.quality_flag_corrupted}")

# =====================================================================
# CELL 17 — TEXT SUMMARY + NUMBERS-FIRST PROMPT
# =====================================================================
def features_to_text(image_id, s):
    """Neutral, flat rendering. No adjectives, no interpretation — any
    judgement in the output must come from the model reasoning over numbers,
    not from language smuggled in here."""
    if s["n_objects"] == 0:
        return (f"Image {image_id}: segmentation detected 0 objects above the "
                f"minimum area threshold of {MIN_OBJECT_AREA} pixels.")
    return (f"Image {image_id}. Segmentation detected {s['n_objects']} distinct objects "
            f"in a {IMG_SIZE} by {IMG_SIZE} pixel field. "
            f"Object area: mean {s['mean_area']} px, median {s['median_area']} px, "
            f"standard deviation {s['std_area']} px. "
            f"Combined object area covers {s['coverage_pct']} percent of the field. "
            f"Mean eccentricity is {s['mean_eccentricity']} (0 = circular, 1 = elongated). "
            f"Mean solidity is {s['mean_solidity']} (1 = fully convex, lower = irregular). "
            f"Mean object intensity is {s['mean_intensity']} on a 0 to 255 scale.")

# density_class uses the dataset's OWN four regimes so it can be scored
# against metadata.csv — a rare chance to measure an LLM classification
# against ground truth.
NUMBERS_FIRST_PROMPT = """You are interpreting quantitative measurements from an
automated microscopy image-segmentation pipeline. You have NOT seen the image.
You have only the measurements below.

Base every statement solely on these numbers. Do not speculate about what the
image depicts, the organism or tissue involved, or any clinical meaning. Do not
invent measurements that are not listed.

MEASUREMENTS:
{summary}

Respond with a single JSON object and nothing else. No preamble, no markdown
fences.

{{
  "description": one paragraph of 2 to 4 sentences describing the object
                 population, referring only to the numbers given,
  "n_objects": integer, copied exactly from the measurements,
  "density_class": one of ["sparse", "normal", "dense", "clustered"],
  "shape_regularity": one of ["regular", "mixed", "irregular"] - judge from mean
                      eccentricity and mean solidity,
  "quality_flag": one of ["ok", "review"] - use "review" if zero objects were
                  detected, if the area standard deviation is large relative to
                  the mean, or if the numbers look internally inconsistent
}}"""

print(features_to_text(rep.image_id,
      otsu_all[otsu_all.image_id==rep.image_id].iloc[0].to_dict()))

# =====================================================================
# CELL 18 (FIXED) — NUMBERS-FIRST INTERPRETATION
# =====================================================================
def query_text_llm(prompt, model=None, timeout=REQUEST_TIMEOUT, force_json=True):
    """Text-only call.

    format="json" makes Ollama constrain decoding to syntactically valid JSON.
    Without it, small models echo whatever structure the prompt shows them —
    which is why a pseudo-schema with unquoted values produces 0% parse rate.
    """
    payload = {"model": model or TEXT_MODEL, "prompt": prompt, "stream": False,
               "options": {"temperature": 0.2}}
    if force_json:
        payload["format"] = "json"
    t0 = time.time()
    r = requests.post(f"{OLLAMA_HOST}/api/generate", json=payload, timeout=timeout)
    r.raise_for_status()
    return {"response": r.json().get("response",""), "elapsed_s": round(time.time()-t0,2)}


def extract_json(text):
    """Fences, preamble, trailing commas, and a brace scan that respects string
    literals (so a '{' inside a description does not derail it)."""
    if not text or not text.strip(): return None, "empty"
    t = text.strip()
    if t.startswith("```"):
        t = re.sub(r"^```(?:json)?\s*", "", t); t = re.sub(r"\s*```$", "", t).strip()

    def _try(s):
        try: return json.loads(s)
        except json.JSONDecodeError: pass
        try: return json.loads(re.sub(r",\s*([}\]])", r"\1", s))   # trailing commas
        except json.JSONDecodeError: return None

    got = _try(t)
    if got is not None: return got, "clean"
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        got = _try(m.group(1))
        if got is not None: return got, "fenced"
    start = text.find("{")
    if start != -1:
        depth, in_str, esc = 0, False, False
        for i, ch in enumerate(text[start:], start):
            if esc: esc = False; continue
            if ch == "\\" and in_str: esc = True; continue
            if ch == '"': in_str = not in_str; continue
            if in_str: continue
            if ch == "{": depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    got = _try(text[start:i+1])
                    if got is not None: return got, "embedded"
                    break
    return None, "unparseable"


# The prompt now shows a CONCRETE, VALID example. The previous version showed a
# pseudo-schema whose "values" were English descriptions — not valid JSON — and
# the model reproduced that structure faithfully, which is exactly what a
# few-shot example is supposed to make it do.
NUMBERS_FIRST_PROMPT = """You are interpreting quantitative measurements from an
automated microscopy image-segmentation pipeline. You have NOT seen the image.
You have only the measurements below.

Base every statement solely on these numbers. Do not speculate about what the
image depicts, the organism or tissue involved, or any clinical meaning. Do not
invent measurements that are not listed.

MEASUREMENTS:
{summary}

Reply with one JSON object matching this exact structure:

{{"description": "A short paragraph describing the object population.", "n_objects": 27, "density_class": "normal", "shape_regularity": "regular", "quality_flag": "ok"}}

Field rules:
- description: 2 to 4 sentences, referring only to the numbers given
- n_objects: integer, copied exactly from the measurements above
- density_class: exactly one of "sparse", "normal", "dense", "clustered"
- shape_regularity: exactly one of "regular", "mixed", "irregular", judged from
  mean eccentricity and mean solidity
- quality_flag: exactly one of "ok", "review". Use "review" if zero objects were
  detected, if the area standard deviation is large relative to the mean, or if
  the numbers look internally inconsistent.

Output only the JSON object."""


ALLOWED_DENSITY = {"sparse","normal","dense","clustered"}
ALLOWED_SHAPE   = {"regular","mixed","irregular"}
ALLOWED_QFLAG   = {"ok","review"}

def validate_numbers_record(rec, computed):
    """Validate the record AND check the echoed count against the computed one."""
    if rec is None: return {"valid": False, "n_objects_matches": False}
    missing = [f for f in ["description","n_objects","density_class",
                           "shape_regularity","quality_flag"] if f not in rec]
    viol = []
    if str(rec.get("density_class","")).lower() not in ALLOWED_DENSITY: viol.append("density_class")
    if str(rec.get("shape_regularity","")).lower() not in ALLOWED_SHAPE: viol.append("shape_regularity")
    if str(rec.get("quality_flag","")).lower() not in ALLOWED_QFLAG: viol.append("quality_flag")
    try:    matches = int(rec.get("n_objects",-1)) == int(computed["n_objects"])
    except (TypeError, ValueError): matches = False
    return {"valid": not missing and not viol, "n_objects_matches": matches}

def interpret_numbers(image_id, summ, model=None):
    prompt = NUMBERS_FIRST_PROMPT.format(summary=features_to_text(image_id, summ))
    raw = query_text_llm(prompt, model=model)
    parsed, status = extract_json(raw["response"])
    chk = validate_numbers_record(parsed, summ)
    return {"image_id": image_id, "parse_status": status, "schema_valid": chk["valid"],
            "n_objects_matches_computed": chk["n_objects_matches"],
            "llm_n_objects": (parsed or {}).get("n_objects"),
            "computed_n_objects": summ["n_objects"],
            "density_class": (parsed or {}).get("density_class"),
            "shape_regularity": (parsed or {}).get("shape_regularity"),
            "quality_flag": (parsed or {}).get("quality_flag"),
            "description": (parsed or {}).get("description"),
            "raw_response": raw["response"][:500],   # keep for the report
            "elapsed_s": raw["elapsed_s"]}

nf_rows = []
for _, r in otsu_all[otsu_all.split=="val"].iterrows():
    try:
        nf_rows.append(interpret_numbers(r.image_id, r.to_dict()))
        print(f"  {r.image_id}: {nf_rows[-1]['parse_status']}, "
              f"n={nf_rows[-1]['llm_n_objects']} (computed {r.n_objects}), "
              f"density={nf_rows[-1]['density_class']}")
    except Exception as e:
        print(f"  {r.image_id}: ERROR {type(e).__name__}: {str(e)[:120]}")

numbers_first = pd.DataFrame(nf_rows).merge(
    manifest[["image_id","density"]], on="image_id", how="left")
numbers_first["density_correct"] = (numbers_first.density_class.str.lower()
                                    == numbers_first.density.str.lower())
numbers_first.to_csv(TAB_DIR/"numbers_first_records.csv", index=False)

print(f"\nparse statuses              : {numbers_first.parse_status.value_counts().to_dict()}")
print(f"schema-valid                : {numbers_first.schema_valid.mean():.1%}")
print(f"n_objects copied correctly  : {numbers_first.n_objects_matches_computed.mean():.1%}")
print(f"density_class vs metadata   : {numbers_first.density_correct.mean():.1%}")
if numbers_first.schema_valid.any():
    print("\nExample narrative:\n", numbers_first[numbers_first.schema_valid].iloc[0]["description"])

# =====================================================================
# CELL 19 — DIRECT VLM vs NUMBERS-FIRST  (report question 1)
# =====================================================================
comparison = pd.DataFrame([
    {"property": "Sees the image",            "vlm_task1": "yes", "numbers_first_task2": "no"},
    {"property": "Output verifiable vs truth", "vlm_task1": "no — no ground truth for modality/tissue",
     "numbers_first_task2": f"yes — density_class scored at {numbers_first.density_correct.mean():.0%}"},
    {"property": "Numeric fields",            "vlm_task1": "none",
     "numbers_first_task2": "from regionprops, not the model"},
    {"property": "Stable across identical calls",
     "vlm_task1": f"{vlm_var[vlm_var.agreement<1.0].shape[0]} of 4 fields varied",
     "numbers_first_task2": "inputs deterministic; prose still varies"},
    {"property": "Schema compliance",
     "vlm_task1": f"{prompt_cmp[prompt_cmp.prompt=='structured'].schema_valid.iloc[0]}",
     "numbers_first_task2": f"{numbers_first.schema_valid.mean():.0%}"},
])
comparison.to_csv(TAB_DIR/"vlm_vs_numbersfirst.csv", index=False)
print(comparison.to_string(index=False))
print("\nThe asymmetry that matters: the VLM's claims cannot be scored at all.")
print("That is not the same as being wrong — it is worse, because it cannot be")
print("caught. The numbers-first claims can be checked, and are.")

"""U-Net"""

# =====================================================================
# CELL 20 — DATASET (uses the PROVIDED splits, not a random split)
# =====================================================================
import torch, torch.nn as nn
from torch.utils.data import Dataset, DataLoader

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE, EPOCHS, LR, BASE_CH, PRED_THRESH = 8, 30, 1e-3, 16, 0.5
torch.manual_seed(RANDOM_STATE)

class NucleiDataset(Dataset):
    def __init__(self, man, split, augment=False):
        self.rows = man[(man.split==split) & man["mask"].notna()].reset_index(drop=True)
        self.augment = augment
    def __len__(self): return len(self.rows)
    def _aug(self, img, m):
        # Flips and 90-degree rotations only: exact (no interpolation) and
        # applied identically to image and mask, so pairing cannot drift.
        k = np.random.randint(4)
        img, m = np.rot90(img,k), np.rot90(m,k)
        if np.random.rand()<.5: img, m = np.fliplr(img), np.fliplr(m)
        if np.random.rand()<.5: img, m = np.flipud(img), np.flipud(m)
        return np.ascontiguousarray(img), np.ascontiguousarray(m)
    def __getitem__(self, i):
        r = self.rows.iloc[i]
        img = load_image_gray(r["image"]).astype(np.float32)/255.
        m   = load_mask(r["mask"]).astype(np.float32)
        if self.augment: img, m = self._aug(img, m)
        return torch.from_numpy(img).unsqueeze(0), torch.from_numpy(m).unsqueeze(0), r["image_id"]

train_ds = NucleiDataset(manifest, "train", augment=True)
val_ds   = NucleiDataset(manifest, "val")
train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_dl   = DataLoader(val_ds, batch_size=1, shuffle=False)
print(f"train {len(train_ds)} | val {len(val_ds)} | device {DEVICE}")

# =====================================================================
# CELL 21 — U-NET  (provided skeleton)
# =====================================================================
class DoubleConv(nn.Module):
    """Two 3x3 convolutions with batch norm and ReLU, the basic U-Net block."""
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True))
    def forward(self, x): return self.block(x)

class UNet(nn.Module):
    def __init__(self, in_ch=1, out_ch=1, base=16):
        super().__init__()
        self.enc1 = DoubleConv(in_ch, base)
        self.enc2 = DoubleConv(base, base*2)
        self.enc3 = DoubleConv(base*2, base*4)
        self.bottleneck = DoubleConv(base*4, base*8)
        self.up3  = nn.ConvTranspose2d(base*8, base*4, 2, stride=2)
        self.dec3 = DoubleConv(base*8, base*4)
        self.up2  = nn.ConvTranspose2d(base*4, base*2, 2, stride=2)
        self.dec2 = DoubleConv(base*4, base*2)
        self.up1  = nn.ConvTranspose2d(base*2, base, 2, stride=2)
        self.dec1 = DoubleConv(base*2, base)
        self.out_conv = nn.Conv2d(base, out_ch, kernel_size=1)
        self.pool = nn.MaxPool2d(2)
    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        b  = self.bottleneck(self.pool(e3))
        d3 = self.dec3(torch.cat([self.up3(b),  e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d3), e2], dim=1))
        d1 = self.dec1(torch.cat([self.up1(d2), e1], dim=1))
        return self.out_conv(d1)   # raw logits

_m = UNet().to(DEVICE)
N_PARAMS = sum(p.numel() for p in _m.parameters())
print(f"U-Net created. Parameter count: {N_PARAMS:,}")
_x = torch.randn(2,1,256,256).to(DEVICE); _y = _m(_x)
print(f"Input {tuple(_x.shape)} -> output {tuple(_y.shape)}")
assert _y.shape == _x.shape
print(f"\n{N_PARAMS/len(train_ds):,.0f} parameters per training image — quote this "
      f"ratio when discussing overfitting.")
del _m, _x, _y

# =====================================================================
# CELL 22 — LOSSES AND METRICS
# =====================================================================
def soft_dice_loss(logits, target, eps=1.0):
    """Differentiable Dice on probabilities — no thresholding, so gradients flow."""
    p = torch.sigmoid(logits)
    num = 2*(p*target).sum(dim=(1,2,3)) + eps
    den = p.sum(dim=(1,2,3)) + target.sum(dim=(1,2,3)) + eps
    return 1 - (num/den).mean()

class CombinedLoss(nn.Module):
    """BCE, Dice, or their sum — selectable for the ablation.

    BCE alone is dominated by background when foreground is sparse: an
    all-background prediction scores well on BCE and zero on Dice. Dice alone
    is unstable early. The sum is usually more reliable than either.
    """
    def __init__(self, mode="bce+dice", dice_weight=0.5):
        super().__init__(); assert mode in {"bce","dice","bce+dice"}
        self.mode, self.w, self.bce = mode, dice_weight, nn.BCEWithLogitsLoss()
    def forward(self, logits, target):
        if self.mode=="bce":  return self.bce(logits, target)
        if self.mode=="dice": return soft_dice_loss(logits, target)
        return (1-self.w)*self.bce(logits,target) + self.w*soft_dice_loss(logits,target)

@torch.no_grad()
def evaluate(model, loader, thresh=PRED_THRESH):
    """Macro AND micro. Macro averages per-image scores so every image counts
    equally; micro pools all pixels so dense images dominate. They diverge when
    object density varies, and reporting one without saying which hides that."""
    model.eval(); ds, ios = [], []; inter = ps = ts = 0.0
    for x, y, _ in loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        lg = model(x); pr = (torch.sigmoid(lg) > thresh).float()
        i_ = (pr*y).sum(dim=(1,2,3)); p_, t_ = pr.sum(dim=(1,2,3)), y.sum(dim=(1,2,3))
        ds.append(((2*i_+1e-7)/(p_+t_+1e-7)).cpu())
        ios.append(((i_+1e-7)/(p_+t_-i_+1e-7)).cpu())
        inter += (pr*y).sum().item(); ps += pr.sum().item(); ts += y.sum().item()
    ds, ios = torch.cat(ds), torch.cat(ios)
    return {"macro_dice": float(ds.mean()), "macro_iou": float(ios.mean()),
            "micro_dice": 2*inter/(ps+ts+1e-7), "micro_iou": inter/(ps+ts-inter+1e-7),
            "dice_std": float(ds.std()) if len(ds)>1 else 0.0,
            "dice_min": float(ds.min()), "dice_max": float(ds.max())}

# =====================================================================
# CELL 23 — TRAINING LOOP
# =====================================================================
def train_unet(loss_mode="bce+dice", epochs=EPOCHS, lr=LR, seed=RANDOM_STATE, verbose=True):
    """Keeps the best-Dice checkpoint, not the final epoch: on 20 validation
    images the score oscillates and the last epoch is not reliably best."""
    torch.manual_seed(seed); np.random.seed(seed)
    model = UNet(1,1,BASE_CH).to(DEVICE)
    crit, opt = CombinedLoss(loss_mode), torch.optim.Adam(model.parameters(), lr=lr)
    sched = torch.optim.lr_scheduler.ReduceLROnPlateau(opt, mode="max", factor=.5, patience=5)
    hist, best, best_state = [], -1.0, None
    for ep in range(1, epochs+1):
        model.train(); run = 0.0
        for x, y, _ in train_dl:
            x, y = x.to(DEVICE), y.to(DEVICE)
            opt.zero_grad(); loss = crit(model(x), y); loss.backward(); opt.step()
            run += loss.item()*x.size(0)
        tr = run/len(train_dl.dataset); val = evaluate(model, val_dl); sched.step(val["macro_dice"])
        hist.append({"epoch": ep, "train_loss": tr, "val_macro_dice": val["macro_dice"],
                     "val_macro_iou": val["macro_iou"], "val_micro_dice": val["micro_dice"]})
        if val["macro_dice"] > best:
            best = val["macro_dice"]
            best_state = {k: v.detach().cpu().clone() for k,v in model.state_dict().items()}
        if verbose and (ep%5==0 or ep==1):
            print(f"  epoch {ep:>3} | loss {tr:.4f} | Dice {val['macro_dice']:.4f} "
                  f"| IoU {val['macro_iou']:.4f}")
    if best_state: model.load_state_dict(best_state)
    return model, pd.DataFrame(hist), best

model, history, best_dice = train_unet("bce+dice")
history.to_csv(TAB_DIR/"unet_training_history.csv", index=False)
final = evaluate(model, val_dl)
print("\nVALIDATION (best checkpoint)")
for k,v in final.items(): print(f"  {k:<12} {v:.4f}")
print(f"\nmacro - micro Dice = {final['macro_dice']-final['micro_dice']:+.4f}")
torch.save(model.state_dict(), PROJECT/"unet_best.pt")

# =====================================================================
# CELL 24 — FIGURE 4: TRAINING CURVES
# =====================================================================
fig, axes = plt.subplots(1, 2, figsize=(11, 3.6))
axes[0].plot(history.epoch, history.train_loss, color=INK, lw=1.4)
axes[0].set_xlabel("epoch"); axes[0].set_ylabel("BCE + Dice loss"); axes[0].set_title("Training loss")
axes[1].plot(history.epoch, history.val_macro_dice, color=SIGNAL, lw=1.4, label="macro Dice")
axes[1].plot(history.epoch, history.val_micro_dice, color=WARM, lw=1.2, ls="--", label="micro Dice")
axes[1].plot(history.epoch, history.val_macro_iou, color=INK, lw=1.0, ls=":", label="macro IoU")
axes[1].set_xlabel("epoch"); axes[1].set_title("Validation metrics"); axes[1].legend(fontsize=8)
fig.tight_layout()
save_fig(fig, 4, "U-Net training loss and validation Dice/IoU by epoch.", "Task 3 — U-Net")
plt.show()
print("A falling loss against a flat validation Dice is the signature of")
print("memorisation — expected with 80 training images.")

# =====================================================================
# CELL 25 — FIGURE 5: PREDICTION PANELS
# =====================================================================
@torch.no_grad()
def plot_predictions(model, ds, n=4, fig_no=5, thresh=PRED_THRESH):
    """Fourth column separates false positives from false negatives — a binary
    overlay hides which. Over- and under-segmentation are different failures."""
    model.eval()
    dens = manifest.set_index("image_id")["density"].to_dict()
    chosen = []
    for w in ["sparse","normal","dense","clustered"]:
        for i in range(len(ds)):
            if dens.get(ds.rows.iloc[i]["image_id"])==w and i not in chosen:
                chosen.append(i); break
    chosen = (chosen + [i for i in range(len(ds)) if i not in chosen])[:n]

    fig, axes = plt.subplots(len(chosen), 4, figsize=(12, 3.0*len(chosen)))
    axes = np.atleast_2d(axes)
    for row, idx in enumerate(chosen):
        x, y, iid = ds[idx]
        pred = (torch.sigmoid(model(x.unsqueeze(0).to(DEVICE)))[0,0].cpu().numpy() > thresh)
        gt = y[0].numpy() > .5
        inter = np.logical_and(pred, gt).sum()
        d = 2*inter/(pred.sum()+gt.sum()+1e-7); i_ = inter/(np.logical_or(pred,gt).sum()+1e-7)
        axes[row,0].imshow(x[0].numpy(), cmap="gray")
        axes[row,0].set_title(f"{iid} ({dens.get(iid)})", fontsize=8)
        axes[row,1].imshow(gt, cmap="gray"); axes[row,1].set_title("ground truth", fontsize=8)
        axes[row,2].imshow(pred, cmap="gray")
        axes[row,2].set_title(f"prediction  Dice {d:.3f} / IoU {i_:.3f}", fontsize=8)
        err = np.zeros((*gt.shape,3))
        err[...,0] = (pred & ~gt); err[...,2] = (~pred & gt); err[pred & gt] = [1,1,1]
        axes[row,3].imshow(err); axes[row,3].set_title("red FP / blue FN", fontsize=8)
        for c in range(4): axes[row,c].axis("off"); axes[row,c].grid(False)
    fig.suptitle("U-Net predictions on held-out validation images", y=0.998)
    fig.tight_layout()
    save_fig(fig, fig_no, "Validation examples spanning density regimes: input, ground "
             "truth, prediction with per-image Dice/IoU, and an error map separating "
             "false positives from false negatives.", "Task 3 — U-Net")
    plt.show()

plot_predictions(model, val_ds, n=4)

# =====================================================================
# CELL 26 — LOSS ABLATION
# =====================================================================
ablation_rows, ablation_models = [], {}
for mode in ["bce", "dice", "bce+dice"]:
    print(f"\n--- loss = {mode} ---")
    m, h, b = train_unet(mode, verbose=False)
    ev = evaluate(m, val_dl); ablation_models[mode] = m
    ablation_rows.append({"loss": mode, **{k: round(v,4) for k,v in ev.items()}})
    print(f"    macro Dice {ev['macro_dice']:.4f} | macro IoU {ev['macro_iou']:.4f}")

ablation = pd.DataFrame(ablation_rows).sort_values("macro_dice", ascending=False)
ablation.to_csv(TAB_DIR/"loss_ablation.csv", index=False)
print("\nLOSS ABLATION — validation set"); print(ablation.to_string(index=False))
BEST_LOSS = ablation.iloc[0]["loss"]
print(f"\nbest by macro Dice: {BEST_LOSS}")
print("Interpret the ordering, don't just report it: check whether BCE alone")
print("under-segments (high micro, low macro) — background dominance is the")
print("mechanism, and the macro/micro gap is where it shows.")

# =====================================================================
# CELL 27 — OTSU vs U-NET  (report question 2)
# =====================================================================
@torch.no_grad()
def segment_unet(img, model, thresh=PRED_THRESH):
    model.eval()
    x = torch.from_numpy(img.astype(np.float32)/255.).unsqueeze(0).unsqueeze(0)
    return (torch.sigmoid(model(x.to(DEVICE)))[0,0].cpu().numpy() > thresh)

def dice_binary(a,b):
    a,b = np.asarray(a,bool), np.asarray(b,bool); d = a.sum()+b.sum()
    return float(2*np.logical_and(a,b).sum()/d) if d else np.nan
def iou_binary(a,b):
    a,b = np.asarray(a,bool), np.asarray(b,bool); u = np.logical_or(a,b).sum()
    return float(np.logical_and(a,b).sum()/u) if u else np.nan

rows = []
for _, r in manifest[(manifest.split=="val") & manifest["mask"].notna()].iterrows():
    img, gt = load_image_gray(r["image"]), load_mask(r["mask"])
    om, _ = segment_otsu(img); um = segment_unet(img, model)
    rows.append({"image_id": r.image_id, "density": r.density, "true_n": int(r.true_n_objects),
                 "otsu_dice": dice_binary(om,gt), "otsu_iou": iou_binary(om,gt),
                 "unet_dice": dice_binary(um,gt), "unet_iou": iou_binary(um,gt),
                 "method_agreement_iou": iou_binary(om,um),
                 "otsu_n": int(label(om).max()), "unet_n": int(label(um).max())})
seg_cmp = pd.DataFrame(rows)
seg_cmp["unet_minus_otsu_dice"] = seg_cmp.unet_dice - seg_cmp.otsu_dice
seg_cmp.to_csv(TAB_DIR/"otsu_vs_unet.csv", index=False)

print(seg_cmp.round(3).to_string(index=False))
print("\nMEAN BY DENSITY")
print(seg_cmp.groupby("density")[["otsu_dice","unet_dice","method_agreement_iou"]].mean().round(3).to_string())
best_u = seg_cmp.loc[seg_cmp.unet_minus_otsu_dice.idxmax()]
best_o = seg_cmp.loc[seg_cmp.unet_minus_otsu_dice.idxmin()]
print(f"\nU-Net best: {best_u.image_id} ({best_u.density}) {best_u.unet_dice:.3f} vs {best_u.otsu_dice:.3f}")
print(f"Otsu best : {best_o.image_id} ({best_o.density}) {best_o.otsu_dice:.3f} vs {best_o.unet_dice:.3f}")
print("\nThese two IDs are the worked examples question 2 asks for.")

# =====================================================================
# CELL 28 — FULL PIPELINE ON THE TEST SET -> CSV
# =====================================================================
REC_DIR = PROJECT/"outputs/records"; REC_DIR.mkdir(parents=True, exist_ok=True)

def run_pipeline(image_path, image_id, model, use_llm=True, segmenter="unet"):
    """U-Net mask -> regionprops -> LLM JSON -> narrative.

    Numeric fields come from regionprops. The LLM contributes classifications
    and prose only. Both the computed and model-reported n_objects are kept so
    divergence is visible in the exported table, not buried in the narrative.
    """
    img  = load_image_gray(image_path)
    mask = segment_unet(img, model) if segmenter=="unet" else segment_otsu(img)[0]
    feats = extract_region_features(mask, img); summ = summarise_regions(feats)
    rec = {"image_id": image_id, "segmenter": segmenter, "n_objects": summ["n_objects"],
           "mean_area": summ["mean_area"], "coverage_pct": summ["coverage_pct"],
           "mean_eccentricity": summ["mean_eccentricity"], "mean_solidity": summ["mean_solidity"]}
    if use_llm:
        try:
            llm = interpret_numbers(image_id, summ)
            rec.update({"density_class": llm["density_class"],
                        "shape_regularity": llm["shape_regularity"],
                        "quality_flag": llm["quality_flag"], "narrative": llm["description"],
                        "llm_n_objects": llm["llm_n_objects"],
                        "n_objects_matches_computed": llm["n_objects_matches_computed"],
                        "parse_status": llm["parse_status"]})
        except Exception as e:
            rec.update({"density_class": None, "shape_regularity": None,
                        "quality_flag": "review", "narrative": None, "llm_n_objects": None,
                        "n_objects_matches_computed": False,
                        "parse_status": f"error: {type(e).__name__}"})
    return rec, mask, feats

test_rows = manifest[manifest.split=="test"]
records = []
for _, r in test_rows.iterrows():
    rec, _, _ = run_pipeline(r["image"], r.image_id, model)
    records.append(rec)
    print(f"  {rec['image_id']}: {rec['n_objects']} objects (true {int(r.true_n_objects)}), "
          f"density={rec.get('density_class')}, quality={rec.get('quality_flag')}")

pipeline_df = pd.DataFrame(records).merge(
    test_rows[["image_id","density","true_n_objects"]], on="image_id", how="left")
pipeline_df.to_csv(REC_DIR/"test_pipeline_records.csv", index=False)
for rec in records:
    (REC_DIR/f"{rec['image_id']}.json").write_text(json.dumps(rec, indent=2, default=str))

print(f"\n{len(pipeline_df)} records -> test_pipeline_records.csv")
print("\nExample JSON record (put one in the report):")
print(json.dumps(records[0], indent=2, default=str)[:900])
print(f"\nn_objects copied correctly: {pipeline_df.n_objects_matches_computed.mean():.1%}")
print(f"density_class vs metadata : "
      f"{(pipeline_df.density_class.str.lower()==pipeline_df.density.str.lower()).mean():.1%}")

# =====================================================================
# CELL 29 — CORRUPTION TRACE (EXTRA CREDIT)
# =====================================================================
# Uses the four PROVIDED corrupted test images rather than injecting new ones,
# so the experiment is reproducible. Four pipeline stages are instrumented.
def bimodality_coefficient(x):
    x = np.asarray(x, float); n = x.size
    if n < 4: return np.nan
    s = x.std(ddof=1)
    if s == 0: return np.nan
    z = (x-x.mean())/s; skew, kurt = np.mean(z**3), np.mean(z**4)-3.0
    den = kurt + 3.0*((n-1)**2)/((n-2)*(n-3))
    return float((skew**2+1.0)/den) if den else np.nan

rows = []
for cp in sorted((ROOT/"test_corrupted/images").glob("*.png")):
    src, kind = cp.stem.rsplit("_", 1)
    clean_p = ROOT/"test/images"/f"{src}.png"
    if not clean_p.exists(): continue
    ci, xi = load_image_gray(clean_p), load_image_gray(cp)
    cm, xm = segment_unet(ci, model), segment_unet(xi, model)
    cs = summarise_regions(extract_region_features(cm, ci))
    xs = summarise_regions(extract_region_features(xm, xi))
    row = {"image": cp.stem, "corruption": kind,
           # stage 1 — image statistics
           "d_mean": round(xi.mean()-ci.mean(), 2), "d_std": round(xi.std()-ci.std(), 2),
           "d_bimodality": round(bimodality_coefficient(xi.ravel()[::7])
                                 - bimodality_coefficient(ci.ravel()[::7]), 3),
           # stage 2 — mask
           "mask_iou_vs_clean": round(iou_binary(xm, cm), 3),
           # stage 3 — feature table
           "n_clean": cs["n_objects"], "n_corrupt": xs["n_objects"],
           "d_mean_area": round(xs["mean_area"]-cs["mean_area"], 1),
           "d_coverage_pct": round(xs["coverage_pct"]-cs["coverage_pct"], 2)}
    try:  # stage 4 — narrative / JSON
        row["quality_flag_corrupted"] = interpret_numbers(cp.stem, xs)["quality_flag"]
    except Exception:
        row["quality_flag_corrupted"] = None
    rows.append(row)

corruption = pd.DataFrame(rows)
corruption.to_csv(TAB_DIR/"corruption_trace.csv", index=False)
print(corruption.to_string(index=False))

print("\nEARLIEST DETECTABLE STAGE")
print("-"*58)
# NOTE: the detector uses STANDARD DEVIATION, not mean. Blur shifts the mean by
# under 1 grey level while halving the object count; a mean-based quality check
# would flag the harmless corruption and miss the damaging one.
for _, r in corruption.iterrows():
    if abs(r.d_std) > 5:                       stage = "1 — image statistics (std)"
    elif r.mask_iou_vs_clean < 0.9:            stage = "2 — segmentation mask"
    elif r.n_corrupt != r.n_clean:             stage = "3 — feature table"
    elif r.quality_flag_corrupted == "review": stage = "4 — narrative only"
    else:                                      stage = "NEVER — passes through undetected"
    print(f"  {r['image']:<26} {stage:<32} maskIoU {r.mask_iou_vs_clean:.3f}  "
          f"count {r.n_clean}->{r.n_corrupt}")
print("\nExpect: low contrast is LOUD at stage 1 but harmless downstream (Otsu")
print("and a normalised U-Net are near-invariant to affine intensity rescaling);")
print("blur is QUIET at stage 1 by mean but destroys the mask. Discuss that")
print("asymmetry — it is the extension's real finding.")

# =====================================================================
# CELL 30 — FIGURE 6: CORRUPTION PROPAGATION
# =====================================================================
src = corruption.iloc[0]["image"].rsplit("_",1)[0]
fig, axes = plt.subplots(2, 3, figsize=(11, 7))
for col, (p, name) in enumerate([
        (ROOT/"test/images"/f"{src}.png", "clean"),
        (ROOT/"test_corrupted/images"/f"{src}_blur.png", "heavy blur"),
        (ROOT/"test_corrupted/images"/f"{src}_lowcontrast.png", "low contrast")]):
    if not Path(p).exists(): continue
    img = load_image_gray(p)
    axes[0,col].imshow(img, cmap="gray", vmin=0, vmax=255)
    axes[0,col].set_title(f"{name}\nmean {img.mean():.1f}, std {img.std():.1f}", fontsize=8)
    m = segment_unet(img, model)
    axes[1,col].imshow(m, cmap="gray")
    axes[1,col].set_title(f"U-Net mask: {label(m).max()} components", fontsize=8)
    for r_ in (0,1): axes[r_,col].axis("off"); axes[r_,col].grid(False)
fig.suptitle(f"Corruption propagation, {src}", y=0.995)
fig.tight_layout()
save_fig(fig, 6, "Provided corrupted test images and resulting U-Net masks. Low "
         "contrast shifts image statistics without changing the mask; blur does the "
         "reverse.", "Extension — robustness")
plt.show()

# =====================================================================
# CELL 31 — EVIDENCE FOR THE FIVE QUESTIONS
# =====================================================================
print("="*72); print("Q1  VLM vs numbers-first"); print("="*72)
print(vlm_var.to_string(index=False))
print(f"\n  vision model used            : {VISION_MODEL}")
print(f"  numbers-first schema-valid   : {numbers_first.schema_valid.mean():.1%}")
print(f"  n_objects copied correctly   : {numbers_first.n_objects_matches_computed.mean():.1%}")
print(f"  density_class vs ground truth: {numbers_first.density_correct.mean():.1%}")
print("  -> The VLM's modality/tissue claims cannot be scored at all. That is")
print("     worse than being wrong: it cannot be caught.")

print("\n"+"="*72); print("Q2  Did U-Net improve on Otsu?"); print("="*72)
print(seg_cmp.groupby("density")[["otsu_dice","unet_dice"]].mean().round(3).to_string())
print(f"\n  overall Otsu {seg_cmp.otsu_dice.mean():.3f} | U-Net {seg_cmp.unet_dice.mean():.3f}")
print(f"  U-Net best example: {best_u.image_id} | Otsu best example: {best_o.image_id}")
print("\n  COUNT CEILING neither method can beat:"); print(decomp.to_string())

print("\n"+"="*72); print("Q3  Dice/IoU meaning and failure modes"); print("="*72)
for k,v in final.items(): print(f"  {k:<12} {v:.4f}")
print(f"  per-image Dice {final['dice_min']:.3f}–{final['dice_max']:.3f} (sd {final['dice_std']:.3f})")
print("\n  worst three validation images:")
print(seg_cmp.nsmallest(3,"unet_dice")[["image_id","density","unet_dice"]].round(3).to_string(index=False))
print(f"\n  {len(train_ds)} training images | {N_PARAMS:,} parameters")
print("\n  LOSS ABLATION:"); print(ablation.to_string(index=False))

print("\n"+"="*72); print("Q4  Where can the LLM hallucinate?"); print("="*72)
bad = numbers_first[~numbers_first.n_objects_matches_computed]
print(f"  altered a number it was told to copy: {len(bad)}/{len(numbers_first)}")
if len(bad): print(bad[["image_id","computed_n_objects","llm_n_objects"]].to_string(index=False))
print(f"  parse statuses: {numbers_first.parse_status.value_counts().to_dict()}")
print("  -> Every numeric field in the CSV comes from regionprops. The LLM")
print("     classifies and narrates only, and even its echoed count is checked.")
print("     The check IS the mitigation, measured rather than asserted.")

print("\n"+"="*72); print("Q5  Clinical trust"); print("="*72)
print(corruption[["image","corruption","d_std","mask_iou_vs_clean","n_clean","n_corrupt"]].to_string(index=False))
print("\n  Weigh: the count ceiling, 20 validation images, a fully synthetic")
print("  dataset with no real biological variation, and the blur/contrast")
print("  asymmetry above — the corruption that matters is the quiet one.")

# =====================================================================
# VARIABILITY vs TEMPERATURE — the experiment the brief actually wants
# =====================================================================
# Default settings produced identical output across 5 runs. That is itself a
# result, but it conflates two causes: low default temperature and constrained
# JSON decoding. Sweeping temperature separates them.
rows = []
for temp in [0.0, 0.8]:
    for i in range(3):
        payload = {"model": VISION_MODEL, "prompt": STRUCTURED_PROMPT,
                   "images": [encode_image(REP_IMAGE)], "stream": False,
                   "options": {"temperature": temp}}
        r = requests.post(f"{OLLAMA_HOST}/api/generate", json=payload, timeout=900)
        parsed, status = extract_json(r.json().get("response",""))
        rows.append({"temperature": temp, "run": i+1, "parse_status": status,
                     "modality": (parsed or {}).get("modality"),
                     "tissue_type": (parsed or {}).get("tissue_type"),
                     "image_quality": (parsed or {}).get("image_quality"),
                     "n_features": len((parsed or {}).get("notable_features", []))})
        print(f"  T={temp} run {i+1}: {rows[-1]['modality']} / {rows[-1]['tissue_type']}")

temp_var = pd.DataFrame(rows)
temp_var.to_csv(TAB_DIR/"variability_vs_temperature.csv", index=False)
print(temp_var.groupby("temperature")[["modality","tissue_type","image_quality"]]
      .nunique().to_string())
print("\nDistinct values per field, by temperature. If T=0 gives 1 and T=0.8")
print("gives more, the identical runs were a decoding-setting artefact, not")
print("evidence that VLMs are deterministic.")

# =====================================================================
# NAIVE vs STRUCTURED VARIABILITY — the contrast the brief wants
# =====================================================================
# The structured prompt was stable across 11 calls. That is not evidence that
# VLMs are deterministic — it is evidence that constraining the output space
# removes the room for variation. The unconstrained naive prompt is the control.
def jaccard(a, b):
    """Word-set overlap between two responses. 1.0 = identical vocabulary."""
    A, B = set(a.lower().split()), set(b.lower().split())
    return len(A & B) / len(A | B) if (A | B) else 1.0

results = {}
for label, prompt, force in [("naive", NAIVE_PROMPT, False),
                             ("structured", STRUCTURED_PROMPT, True)]:
    texts = []
    for i in range(3):
        payload = {"model": VISION_MODEL, "prompt": prompt,
                   "images": [encode_image(REP_IMAGE)], "stream": False,
                   "options": {"temperature": 0.8}}
        if force:
            payload["format"] = "json"      # never applied to the naive prompt:
                                            # its failure to produce JSON IS the finding
        r = requests.post(f"{OLLAMA_HOST}/api/generate", json=payload, timeout=900)
        t = r.json().get("response", "").strip()
        texts.append(t)
        print(f"  {label} run {i+1}: {len(t)} chars")
    pairs = [jaccard(texts[i], texts[j]) for i in range(3) for j in range(i+1, 3)]
    results[label] = {"mean_chars": int(np.mean([len(t) for t in texts])),
                      "char_sd": round(float(np.std([len(t) for t in texts])), 1),
                      "mean_pairwise_jaccard": round(float(np.mean(pairs)), 3),
                      "identical_pairs": sum(1 for i in range(3) for j in range(i+1,3)
                                             if texts[i] == texts[j])}
    results[label]["_texts"] = texts

var_cmp = pd.DataFrame({k: {kk: vv for kk, vv in v.items() if not kk.startswith("_")}
                        for k, v in results.items()}).T
var_cmp.to_csv(TAB_DIR/"naive_vs_structured_variability.csv")
print("\n" + var_cmp.to_string())
print("\nJaccard near 1.0 = same words every time. Lower = the model rewrote it.")
print("\n--- naive, three runs (excerpt) ---")
for i, t in enumerate(results["naive"]["_texts"], 1):
    print(f"\n[run {i}] {t[:220]}")

(TAB_DIR/"naive_responses_verbatim.txt").write_text(
    "\n\n---\n\n".join(f"[run {i}]\n{t}" for i, t in enumerate(results["naive"]["_texts"], 1)))
print("saved for quoting in the report")

# =====================================================================
# CELL 32 — MANIFEST + DOWNLOAD
# =====================================================================
man = pd.DataFrame(FIGURES).T.sort_index()[["figure","file","section","caption"]]
man.to_csv(TAB_DIR/"figure_manifest.csv", index=False)
lines = ["# Figure manifest",""]
for _, r in man.iterrows():
    lines += [f"**{r['figure']}** - `{r['file']}` - {r['section']}", "", f"> {r['caption']}", ""]
(FIG_DIR/"FIGURES.md").write_text("\n".join(lines))
print(man.to_string(index=False))

shutil.make_archive("/content/biomed-pipeline", "zip", PROJECT)
from google.colab import files
files.download("/content/biomed-pipeline.zip")